### ISSUE TITLE
Using rework with sass

### ISSUE THREAD

**Issue by st32lthx** [aaronj1335/rework-webpack-loader#6]
Was wondering if it is possible to use rework with the sass-loader to avoid duplication if I use import twice in two sass files ? Something like:

```
loaders: [
      {test: /\.scss$/, loader: 'style-loader!rework-webpack-loader!sass-loader'}
]
```

I tried it, but when I read the `bundle.js`, I don't quite get what I am looking for.

Thanks!

**Comment by aaronj1335** [comment]
hey @aminmeyghani, i don't think this is possible. sass will recursively resolve and inline `@import`'s, so by the time rework-webpack-loader gets to the file, it has no `@import`'s. if you want css files to be treated like the js files in the rework dependency graph, you'll need to drop sass.

this project is actually supplanted by [aaronj1335/webpack-postcss-tools](https://github.com/aaronj1335/webpack-postcss-tools). with that project you can have both the `@import` de-duplication, and a lot of the sass features you're might want, such as variables. if you don't already have a substantial sass codebase, you might look at migrating to postcss plugins. it has some really powerful stuff that sass doesn't even have, such as [postcss/autoprefixer](https://github.com/postcss/autoprefixer).

**Comment by st32lthx** [comment]
Thanks @aaronj1335! I will give it a try.
